/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package case_sync;

import java.io.File;
import java.sql.*;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;

/**
 *
 * @author Hitesh Gupta
 */
public class CaseSync extends javax.swing.JFrame {

    /**
     * Creates new form CaseSync2
     */
    public CaseSync() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pdflist = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/case_sync/black_texture-t2.jpg"))); // NOI18N

        jPanel2.add(jPanel3);

        jButton2.setText("jButton2");
        jPanel2.add(jButton2);

        jPanel1.setLayout(null);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 150, 73, 23);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 180, 120, 20);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASE SYNC");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel6.setLayout(null);

        jButton3.setText("CLICK TO AUTO SYNC");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(110, 130, 170, 23);

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jPanel6.add(jLabel3);
        jLabel3.setBounds(130, 160, 140, 30);

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("WARNING:If app got black wait to complete of work.");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(10, 200, 360, 14);

        jLabel17.setText("*BE PATIENCE");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(40, 20, 290, 14);

        jLabel18.setText("*UNTIL BUTTON IS DARK WORK IS GOING ON");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(40, 40, 320, 14);

        jLabel19.setText("*IT WILL AUTOMATICALLY DOWNLOAD ALL LIST OF TOMMOROW");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(40, 60, 370, 14);

        jLabel20.setText("*IF ANY LIST LEFT DO IT AGAIN ");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(40, 80, 320, 14);

        jTabbedPane2.addTab("AUTO SYNC", jPanel6);

        jPanel7.setLayout(null);

        jButton4.setText("REGULAR DIVISION BENCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);
        jButton4.setBounds(33, 110, 200, 23);

        jButton5.setText("REGULAR SINGLE BENCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);
        jButton5.setBounds(33, 150, 200, 23);

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jPanel7.add(jLabel4);
        jLabel4.setBounds(260, 110, 60, 20);

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jPanel7.add(jLabel5);
        jLabel5.setBounds(260, 150, 50, 20);

        jLabel11.setText("*BE PATIENCE");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(40, 30, 300, 14);

        jLabel12.setText("*UNTIL BUTTON IS DARK WORK IS GOING ON");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(40, 60, 320, 14);

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("WARNING:If app got black wait to complete of work.");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(0, 190, 350, 14);

        jTabbedPane2.addTab("REGULAR MAIN", jPanel7);

        jPanel8.setLayout(null);

        jButton6.setText("BROWSE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6);
        jButton6.setBounds(260, 90, 90, 23);

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jPanel8.add(jLabel6);
        jLabel6.setBounds(260, 124, 110, 20);

        pdflist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdflistActionPerformed(evt);
            }
        });
        jPanel8.add(pdflist);
        pdflist.setBounds(100, 90, 130, 20);

        jButton7.setText("SYNC");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7);
        jButton7.setBounds(119, 120, 100, 23);

        jLabel7.setText("*BROWSE LIST AND THEN SYNC ");
        jPanel8.add(jLabel7);
        jLabel7.setBounds(60, 10, 260, 14);

        jLabel8.setText("*BE PATIENCE");
        jPanel8.add(jLabel8);
        jLabel8.setBounds(60, 30, 270, 14);

        jLabel9.setText("*UNTIL BUTTON IS DARK WORK IS GOING ON");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(60, 50, 290, 14);

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("WARNING:If app got black wait to complete of work.");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(0, 170, 390, 14);

        jTabbedPane2.addTab("MANUAL SYNC", jPanel8);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  
        
        String url = "jdbc:mysql://localhost:3306/";
    String dbName = "cs";
     String driver = "com.mysql.jdbc.Driver";
     String userName = "root"; 
    String password = "30121993";
        list_main u=new list_main();
       Date today = new Date();
       Date tomorrow = new Date(today.getTime() + (1000 * 60 * 60 * 24));
       String modifiedDate;
       modifiedDate = new SimpleDateFormat("yyyy_MM_dd_").format(tomorrow);
       String sql_stmnt;
        Statement s1;
        ResultSet rs;
      
      try{
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(url+dbName,userName,password);
            s1=conn.createStatement();
            sql_stmnt="SELECT * FROM sync_record ";
            rs=s1.executeQuery(sql_stmnt);
            while(rs.next())
            {
       String filenam="C://CaseSync//"+modifiedDate+rs.getString("file_type")+".pdf";
       String address="http://highcourtchd.gov.in/data/"+modifiedDate+rs.getString("file_type")+".pdf";
        int i=filenam.indexOf(".pdf");
       String j=filenam.substring(i-3,i);
       String d=filenam.substring(i-6,i-4);
       String m=filenam.substring(i-9,i-7);
       String y=filenam.substring(i-14,i-10);
       
       try{
        DownloadFile.download(address,filenam);
       }catch(Exception e){System.out.print(e);};
       try{
       int h=u.main_method(filenam,j,d,m,y);
       }catch(Exception e){System.out.print(e);};
       try{
       deletefile.delte(filenam);
       }catch(Exception e){System.out.print(e);};
            }
            rs.close();
       s1.close();
        conn.close();
        }catch(Exception e) { System.out.println(e);} 
      jLabel3.setText("DONE!!!!");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling String filenam="C://CaseSync//"+modifiedDate+rs.getString("file_type")+".pdf";
       String address="http://highcourtchd.gov.in/data/regdb.pdf";
       String filenam="C:\\CaseSync\\regdb.pdf";
       
       int i=filenam.indexOf(".pdf");
       String j=filenam.substring(i-3,i);
       String d=filenam.substring(i-6,i-4);
       String m=filenam.substring(i-9,i-7);
       String y=filenam.substring(i-14,i-10);
       list_main u=new list_main();
       try{
        DownloadFile.download(address,filenam);
       }catch(Exception e){System.out.print(e);};
       try{
       int h=u.main_method(filenam,j,d,m,y);
       }catch(Exception e){System.out.print(e);};
       try{
       deletefile.delte(filenam);
       }catch(Exception e){System.out.print(e);};
        jLabel4.setText("DONE!!!!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         // TODO add your handling String filenam="C://CaseSync//"+modifiedDate+rs.getString("file_type")+".pdf";
       String address="http://highcourtchd.gov.in/data/regsb.pdf";
       String filenam="C://CaseSync//regsb.pdf";
       
       int i=filenam.indexOf(".pdf");
       String j=filenam.substring(i-3,i);
       String d=filenam.substring(i-6,i-4);
       String m=filenam.substring(i-9,i-7);
       String y=filenam.substring(i-14,i-10);
       list_main u=new list_main();
       try{
        DownloadFile.download(address,filenam);
       }catch(Exception e){System.out.print(e);};
       try{
       int h=u.main_method(filenam,j,d,m,y);
       }catch(Exception e){System.out.print(e);};
       try{
       deletefile.delte(filenam);
       }catch(Exception e){System.out.print(e);};
        jLabel5.setText("DONE!!!!");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pdflistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdflistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdflistActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
list_main u=new list_main();
       String filenam;
       filenam = pdflist.getText();
       int i=filenam.indexOf(".pdf");
       String j=filenam.substring(i-3,i);
       String d=filenam.substring(i-6,i-4);
       String m=filenam.substring(i-9,i-7);
       String y=filenam.substring(i-14,i-10);
       try{
       int h=u.main_method(filenam,j,d,m,y);
       if(h==1)
           jLabel6.setText("Done");
       else
           jLabel6.setText("WRONG FILE");
       }catch(Exception e){System.out.print(e);};        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File list =chooser.getSelectedFile();
        String filename=list.getAbsolutePath();
        pdflist.setText(filename);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaseSync.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaseSync.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaseSync.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaseSync.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaseSync().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField pdflist;
    // End of variables declaration//GEN-END:variables
}
